# Generated by Django 3.2 on 2021-07-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0005_auto_20210708_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('music_description', models.CharField(max_length=1000)),
                ('music_category', models.CharField(default='', max_length=50)),
                ('music_subcategory', models.CharField(default='', max_length=50)),
                ('music_price', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('band', models.CharField(default='', max_length=1000)),
                ('special_mention', models.CharField(default='', max_length=1000)),
                ('list_songs', models.CharField(default='', max_length=500)),
                ('music_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('music_link', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='band',
        ),
        migrations.RemoveField(
            model_name='product',
            name='list_songs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_mention',
        ),
    ]
