# Generated by Django 3.2 on 2021-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0006_auto_20210708_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_strike_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
