# Generated by Django 3.2 on 2021-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0007_music_music_strike_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ayurveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
