# Generated by Django 3.2 on 2021-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0008_ayurveda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=4000)),
            ],
        ),
    ]
