# Generated by Django 3.2 on 2021-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0011_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=50)),
                ('size', models.CharField(default='', max_length=2)),
                ('gender', models.CharField(default='', max_length=6)),
                ('foot_size', models.IntegerField(default=0)),
                ('warranty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('off_site', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('wm_capacity', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('ac_type', models.CharField(default='', max_length=100)),
                ('ac_ton', models.IntegerField(default=0)),
                ('tv_size', models.IntegerField(default=0)),
                ('tv_resolution', models.IntegerField(default=0)),
                ('tv_refresh_rate', models.IntegerField(default=0)),
                ('d1', models.CharField(max_length=1000)),
                ('d2', models.CharField(max_length=1000)),
                ('d3', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('off_site', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('app_size', models.IntegerField(default=0)),
                ('no_of_downloads', models.CharField(default='0', max_length=10)),
                ('age_required', models.IntegerField(default=0)),
                ('pd_os', models.CharField(default='', max_length=100)),
                ('anti_os', models.CharField(default='', max_length=100)),
                ('anti_subs', models.IntegerField(default=0)),
                ('gaming_platform', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('off_site', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('associated_sport', models.CharField(default=' ', max_length=100)),
                ('category', models.CharField(default=' ', max_length=100)),
                ('cricketbat_size', models.CharField(default='', max_length=100)),
                ('cricketbat_willow', models.CharField(default='', max_length=100)),
                ('football_size', models.IntegerField(default=0)),
                ('football_weight', models.IntegerField(default=0)),
                ('tt_material', models.CharField(default=' ', max_length=100)),
                ('d1', models.CharField(default=' ', max_length=1000)),
                ('d2', models.CharField(default=' ', max_length=1000)),
                ('d3', models.CharField(default=' ', max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('off_site', models.URLField(default='', max_length=1000)),
            ],
        ),
    ]
