# Generated by Django 3.2 on 2021-07-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0013_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='your_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='shop_name',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='your_phone',
            new_name='shop',
        ),
    ]
