# Generated by Django 3.2 on 2021-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0015_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='books_in_pack',
            field=models.CharField(default='', max_length=500),
        ),
    ]
