# Generated by Django 3.2 on 2021-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0018_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='Art_image',
        ),
        migrations.AlterField(
            model_name='art_n_interior_designing',
            name='Art_image',
            field=models.ImageField(default='', null=True, upload_to='Vyas/images'),
        ),
    ]
