# Generated by Django 3.2 on 2021-07-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0026_auto_20210723_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_n_interior_designing',
            name='path',
        ),
        migrations.RemoveField(
            model_name='book',
            name='path',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='path',
        ),
        migrations.RemoveField(
            model_name='education',
            name='path',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='path',
        ),
        migrations.RemoveField(
            model_name='home_appliances',
            name='path',
        ),
        migrations.RemoveField(
            model_name='music',
            name='path',
        ),
        migrations.RemoveField(
            model_name='pch',
            name='path',
        ),
        migrations.RemoveField(
            model_name='software',
            name='path',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='path',
        ),
        migrations.AddField(
            model_name='art_n_interior_designing',
            name='prod_path',
            field=models.CharField(default='/Vyas/Art/', max_length=108),
        ),
        migrations.AddField(
            model_name='book',
            name='prod_path',
            field=models.CharField(default='/Vyas/Book/', max_length=108),
        ),
        migrations.AddField(
            model_name='clothing',
            name='prod_path',
            field=models.CharField(default='/Vyas/Clothing/', max_length=108),
        ),
        migrations.AddField(
            model_name='education',
            name='prod_path',
            field=models.CharField(default='/Vyas/education/', max_length=108),
        ),
        migrations.AddField(
            model_name='grocery',
            name='prod_path',
            field=models.CharField(default='/Vyas/grocery/', max_length=108),
        ),
        migrations.AddField(
            model_name='home_appliances',
            name='prod_path',
            field=models.CharField(default='/Vyas/Home_Appliances/', max_length=108),
        ),
        migrations.AddField(
            model_name='music',
            name='prod_path',
            field=models.CharField(default='/Vyas/Music/', max_length=108),
        ),
        migrations.AddField(
            model_name='pch',
            name='prod_path',
            field=models.CharField(default='/Vyas/PCH/', max_length=108),
        ),
        migrations.AddField(
            model_name='software',
            name='prod_path',
            field=models.CharField(default='/Vyas/Software/', max_length=108),
        ),
        migrations.AddField(
            model_name='sports',
            name='prod_path',
            field=models.CharField(default='/Vyas/Sports/', max_length=108),
        ),
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.CharField(default='/Vyas/Prodview1/', max_length=108),
        ),
    ]
