# Generated by Django 3.2 on 2021-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0003_auto_20210707_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
