# Generated by Django 3.2 on 2021-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0004_product_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='band',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='list_songs',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='special_mention',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
