# Generated by Django 3.2 on 2021-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0010_auto_20210712_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(default='', max_length=100)),
                ('education_strike_price', models.CharField(default='', max_length=50)),
                ('Company', models.CharField(default='', max_length=1000)),
                ('education_description', models.CharField(default='', max_length=1000)),
                ('education_category', models.CharField(default='', max_length=50)),
                ('education_subcategory', models.CharField(default='', max_length=50)),
                ('education_price', models.IntegerField(default=0)),
                ('education_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('education_link', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
