# Generated by Django 3.2 on 2021-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0014_auto_20210712_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
