# Generated by Django 3.2 on 2021-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0016_auto_20210713_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_N_Interior_Designing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Art_name', models.CharField(default='', max_length=2000)),
                ('Art_company', models.CharField(default='', max_length=2000)),
                ('Art_type', models.CharField(default='', max_length=2000)),
                ('for_place', models.CharField(default='', max_length=5000)),
                ('Art_price', models.IntegerField(default=0)),
                ('Art_description', models.CharField(default='', max_length=300000)),
                ('publish_date', models.DateField()),
                ('Art_image', models.ImageField(default='', upload_to='Vyas/images')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=50)),
                ('Class', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('book_price', models.IntegerField(default=0)),
                ('book_description', models.CharField(default='', max_length=300000)),
                ('publisher', models.CharField(default='', max_length=60)),
                ('book_image', models.ImageField(default='', upload_to='Vyas/images')),
            ],
        ),
        migrations.CreateModel(
            name='grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=5000)),
                ('category', models.CharField(default='', max_length=5000)),
                ('sub_category', models.CharField(default='', max_length=5000)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300000)),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='Vyas/images')),
            ],
        ),
        migrations.CreateModel(
            name='PCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCH_name', models.CharField(default='', max_length=5000)),
                ('PCH_type', models.CharField(default='', max_length=5000)),
                ('PCH_company', models.CharField(default='', max_length=5000)),
                ('PCH_price', models.IntegerField(default=0)),
                ('PCH_description', models.CharField(default='', max_length=300000)),
                ('PCH_publish_date', models.DateField()),
                ('PCH_image', models.ImageField(default='', upload_to='Vyas/images')),
            ],
        ),
    ]
