# Generated by Django 3.2 on 2021-07-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0017_art_n_interior_designing_book_grocery_pch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description_index', models.CharField(default='', max_length=5000)),
                ('index_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('Art_image', models.ImageField(default='', upload_to='Vyas/images')),
                ('path', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
