# Generated by Django 3.2 on 2021-07-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0019_auto_20210722_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_order', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('order_id', models.IntegerField(default=0)),
                ('order_status', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
