# Generated by Django 3.2 on 2021-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0025_alter_ayurveda_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayurveda',
            name='path',
        ),
        migrations.AddField(
            model_name='ayurveda',
            name='prod_path',
            field=models.CharField(default='/Vyas/ayurveda/', max_length=108),
        ),
    ]
