# Generated by Django 3.2 on 2021-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0027_auto_20210723_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='', max_length=100),
        ),
    ]
