# Generated by Django 3.2 on 2021-07-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0028_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
