# Generated by Django 3.2 on 2021-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0029_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='shop',
            field=models.CharField(default='', max_length=100),
        ),
    ]
