# Generated by Django 3.2 on 2021-07-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0030_contact_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
