# Generated by Django 3.2 on 2021-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0031_orders_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_n_interior_designing',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ayurveda',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='education',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='grocery',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='home_appliances',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='music',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pch',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='software',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sports',
            name='sub_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
